version: '3'

services:
  # Сервіс для MySQL бази даних
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaadin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Сервіс для Spring Boot Vaadin додатку
  springbootapp:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_vaadin_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vaadin
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:
    driver: local