name: Deploy to Virtual Machine

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Docker Compose file to VM
        run: scp -o StrictHostKeyChecking=no docker-compose.yml pasha@172.17.0.1:/spring-app/docker-compose.yml

      - name: SSH into VM and start Docker container
        run: ssh -o StrictHostKeyChecking=no pasha@172.17.0.1 'cd /spring-app && docker-compose up -d'
